/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reader_app_YouYouApplication */

#ifndef _Included_com_reader_app_YouYouApplication
#define _Included_com_reader_app_YouYouApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reader_app_YouYouApplication
 * Method:    initInternal
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_reader_app_YouYouApplication_initInternal
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
