/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reader_util_BitmapUtil */

#ifndef _Included_com_reader_util_BitmapUtil
#define _Included_com_reader_util_BitmapUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reader_util_BitmapUtil
 * Method:    DrawBatteryBitmap
 * Signature: (Landroid/graphics/Bitmap;II)I
 */
JNIEXPORT jint JNICALL Java_com_reader_util_BitmapUtil_DrawBatteryBitmap
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
